import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import { Geist_Mono, Libre_Caslon_Text, Cabin } from "next/font/google";
import Navbar from "@/components/Navbar";
import RootWrapper from "@/hooks/root-wrapper";


const serifFont = Libre_Caslon_Text({ subsets: ["latin"], variable: "--font-heading", weight: "400" });
const sansFont = Cabin({ subsets: ["latin"], variable: "--font-sans", weight: "400" });
const monoFont = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

type RootLayoutProps = { children: ReactNode };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en" className={`antialiased ${monoFont.variable} font-sans ${sansFont.variable} ${serifFont.variable}`}>
      <body className="min-h-full flex flex-col">
        <RootWrapper>
          <Navbar />
          {children}
        </RootWrapper>
      </body>
    </html>
  );
}
